// Code generated by protoc-gen-go. DO NOT EDIT.
// source: QuadTree.proto

package quadtree_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ImageQuadtree struct {
	Data                 []uint64 `protobuf:"fixed64,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageQuadtree) Reset()         { *m = ImageQuadtree{} }
func (m *ImageQuadtree) String() string { return proto.CompactTextString(m) }
func (*ImageQuadtree) ProtoMessage()    {}
func (*ImageQuadtree) Descriptor() ([]byte, []int) {
	return fileDescriptor_QuadTree_1608be90320ab040, []int{0}
}
func (m *ImageQuadtree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageQuadtree.Unmarshal(m, b)
}
func (m *ImageQuadtree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageQuadtree.Marshal(b, m, deterministic)
}
func (dst *ImageQuadtree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageQuadtree.Merge(dst, src)
}
func (m *ImageQuadtree) XXX_Size() int {
	return xxx_messageInfo_ImageQuadtree.Size(m)
}
func (m *ImageQuadtree) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageQuadtree.DiscardUnknown(m)
}

var xxx_messageInfo_ImageQuadtree proto.InternalMessageInfo

func (m *ImageQuadtree) GetData() []uint64 {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ImageQuadtree)(nil), "quadtree_proto.ImageQuadtree")
}

func init() { proto.RegisterFile("QuadTree.proto", fileDescriptor_QuadTree_1608be90320ab040) }

var fileDescriptor_QuadTree_1608be90320ab040 = []byte{
	// 90 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0b, 0x2c, 0x4d, 0x4c,
	0x09, 0x29, 0x4a, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2b, 0x2c, 0x4d, 0x4c,
	0x29, 0x29, 0x4a, 0x4d, 0x8d, 0x07, 0xf3, 0x95, 0xd4, 0xb9, 0x78, 0x3d, 0x73, 0x13, 0xd3, 0x53,
	0x03, 0xa1, 0xc2, 0x42, 0x62, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x12, 0x8c, 0x0a, 0xcc, 0x1a,
	0x6c, 0x4e, 0x4c, 0x02, 0x8c, 0x41, 0x60, 0x7e, 0x12, 0x1b, 0x58, 0xbd, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x17, 0x6d, 0x5f, 0x8f, 0x51, 0x00, 0x00, 0x00,
}
