// Code generated by protoc-gen-go. DO NOT EDIT.
// source: QuadTree.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImageQuadtree struct {
	Data                 []uint32 `protobuf:"fixed32,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageQuadtree) Reset()         { *m = ImageQuadtree{} }
func (m *ImageQuadtree) String() string { return proto.CompactTextString(m) }
func (*ImageQuadtree) ProtoMessage()    {}
func (*ImageQuadtree) Descriptor() ([]byte, []int) {
	return fileDescriptor_b82718028510fc03, []int{0}
}

func (m *ImageQuadtree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageQuadtree.Unmarshal(m, b)
}
func (m *ImageQuadtree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageQuadtree.Marshal(b, m, deterministic)
}
func (m *ImageQuadtree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageQuadtree.Merge(m, src)
}
func (m *ImageQuadtree) XXX_Size() int {
	return xxx_messageInfo_ImageQuadtree.Size(m)
}
func (m *ImageQuadtree) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageQuadtree.DiscardUnknown(m)
}

var xxx_messageInfo_ImageQuadtree proto.InternalMessageInfo

func (m *ImageQuadtree) GetData() []uint32 {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ImageQuadtree)(nil), "proto.ImageQuadtree")
}

func init() { proto.RegisterFile("QuadTree.proto", fileDescriptor_b82718028510fc03) }

var fileDescriptor_b82718028510fc03 = []byte{
	// 84 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0b, 0x2c, 0x4d, 0x4c,
	0x09, 0x29, 0x4a, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xea,
	0x5c, 0xbc, 0x9e, 0xb9, 0x89, 0xe9, 0xa9, 0x20, 0xd9, 0x92, 0xa2, 0xd4, 0x54, 0x21, 0x31, 0x2e,
	0x96, 0x94, 0xc4, 0x92, 0x44, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x76, 0x27, 0x26, 0x01, 0xc6, 0x20,
	0x30, 0x3f, 0x89, 0x0d, 0xac, 0xde, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x96, 0x84, 0x9b, 0x88,
	0x48, 0x00, 0x00, 0x00,
}
